### ISSUE TITLE
非标题的多行块能支持标题那样的语法吗?

### ISSUE THREAD

**Issue by exam-ple** [Jasper-1024/block-link-plus#1]
像下面这样, 这样好像会更简洁些. 比如文本块有20行的话, 如果像原先那个语法, 那得列出20个[[file#˅id]] 😥

```
abc ˅id
def
gh ^id

[[file#˅id]]
```

我也一直在找能实现类似功能的, 算是遇到知音了 😀 感谢好插件  🌹

**Comment by Jasper-1024** [comment]
> 像下面这样, 这样好像会更简洁些. 比如文本块有20行的话, 如果像原先那个语法, 那得列出20个[[file#˅id]] 😥
> 
> ```
> abc ˅id
> def
> gh ^id
> 
> [[file#˅id]]
> ```
> 
> 我也一直在找能实现类似功能的, 算是遇到知音了 😀 感谢好插件 🌹

不支持的,  非标题的 块引用 只能是单行.
类似的功能官方的讨论: https://forum.obsidian.md/t/block-reference-for-multiple-paragraph/7674
这个是 madrkdown 支持的问题, obsidian 短时间内无望解决. 从 2020 年挂到现在了...
