### ISSUE TITLE
The Block ID is positioned incorrectly.

### ISSUE THREAD

**Issue by hyperphysin** [Jasper-1024/block-link-plus#3]
![Screenshot 2024-09-19 at 11 11 18 PM](https://github.com/user-attachments/assets/3687c2d1-98c0-4c9f-be28-1d4138b87f44)

Pressing the hotkey when the cursor is next to b creates a block ID next to c.

**Comment by Jasper-1024** [comment]
The position of block id is correct. When obsidian parses markdown into ast, a list is parsed as a block, so when inserting block id, it will be at the last line of this list.

But there is indeed a problem here. When actually rendering, such a list can only display one line.

I will try to treat list as a special case, but there is no guarantee that it will be solved.

**Comment by Jasper-1024** [comment]
Done: https://github.com/Jasper-1024/block-link-plus/releases/tag/1.0.5

**Comment by Jasper-1024** [comment]
@hyperphysin Done: https://github.com/Jasper-1024/block-link-plus/releases/tag/1.0.5
