### ISSUE TITLE
Option to automatically add the name of the header as an alias when copying/pasting link to heading

### ISSUE THREAD

**Issue by albertoloscerritos** [Jasper-1024/block-link-plus#4]
Hi, thanks for your awesome plugin. I just discovered it.
Given that its functionality is very similar (improved) to the copy block link plugin, I wanted to ask for the following [FR] which was never implemented for the original plugin: 
The issue is that, currently it displays the link to a header with the following format: [[note#heading]] which become a hassle because each time I need to manually add an alias to the link. So, I am looking for a solution to automatically add the name of the heading as the alias i.e. [[note#heading|heading]] 

Btw this problem was also documented in the following GitHub issue: [[FR]: Add a commadng to set selected text as an alias for the inserted block reference · Issue #17 · mgmeyers/obsidian-copy-block-link · GitHub 4](https://github.com/mgmeyers/obsidian-copy-block-link/issues/17#issuecomment-1694850018)

Thanks for reading :)

**Comment by greetclammy** [comment]
I support adding this as an option 👍

**Comment by Jasper-1024** [comment]
There are some duplications with https://github.com/Jasper-1024/block-link-plus/issues/5, merged
