### ISSUE TITLE
FR: Copy URL to block

### ISSUE THREAD

**Issue by greetclammy** [Jasper-1024/block-link-plus#6]
I'd be great if this plugin added an additional command to copy a URL to block instead of an internal link. I cobbled together a *Templater* script to achieve this. But having this feature in a plugin would be preferable. Please see my post on the forum: https://forum.obsidian.md/t/copy-url-to-block-command/93286

Also requested this for _Copy Block Link_: https://github.com/mgmeyers/obsidian-copy-block-link/issues/34

**Comment by Jasper-1024** [comment]
This requirement is relatively easy to implement. In theory, all you need to do is add a right-click menu option.

**Comment by greetclammy** [comment]
Yes, I've done so with *Commander*. But it'd be nice to have this as part of the plugin (maybe as a toggleable option in settings).

**Comment by Jasper-1024** [comment]
Done: https://github.com/Jasper-1024/block-link-plus/releases/tag/1.0.6

**Comment by greetclammy** [comment]
Great, thank you! I would name the command "Copy Obsidian URL to block" but this is a nitpick.

**Comment by greetclammy** [comment]
Caught a weird bug in Live Preview:
```
---
tags:
---
| Header 1 | Header 2 |
| -------- | -------- |
| Cell 3   | Cell 2   |
```

When any of the plugin commands are run for e.g. `Header 1`, the output is:
```
---
tags:
--- ^tb9s
| Header 1 | Header 2 |
| -------- | -------- |
| Cell 3   | Cell 2   |
```

I reported a very similar Obsidian bug recently: https://forum.obsidian.md/t/rename-this-block-id-not-working-in-page-preview-messes-up-frontmatter-instead/93310

**Comment by greetclammy** [comment]
@Jasper-1024 I noticed that the plugin copies a URL with the `.md` extension in it e.g.:

```
obsidian://open?vault=Obsidian Sandbox&file=Untitled.md%23%5E8bwb
```

This is redundant because the URL will work the same with or without the `.md` extension e.g. this is a valid URL:

```
obsidian://open?vault=Obsidian Sandbox&file=Untitled%23%5E8bwb
```

If you run the native Obsidian command "Copy Obsidian URL", it will output a link without the `.md` extension e.g.:
```
obsidian://open?vault=Obsidian%20Sandbox&file=Untitled
```

Also, the plugin should percent encode spaces in URLs i.e. turn whitespace into `%20`. You may see in the examples above that the plugin doesn't percent encode whitespace, unlike the native command.
