### ISSUE TITLE
[FR] Option to remove elements from the context menu

### ISSUE THREAD

**Issue by albertoloscerritos** [Jasper-1024/block-link-plus#8]
Hi good morning. Awesome plugin.

One feature that I think would be a great addition is the option to select (in the plugin's settings menu) which elements to show/hide in context menu, e.g. I practically never use the copy to obsidian URL option:
![image](https://github.com/user-attachments/assets/a82dd366-b803-4ea5-862f-17e4b82dd33b)
So, I would prefer to remove that option to reduce clutter from my context menu. 
Thanks for reading.

**Comment by Jasper-1024** [comment]
done: https://github.com/Jasper-1024/block-link-plus/releases/tag/1.1.0
so don't forget star 😋

**Comment by albertoloscerritos** [comment]
Awsome thanks :)
And sure, this plugin deserves all the stars ⭐🤩
